# Generated by Django 4.1.5 on 2023-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=30)),
            ],
        ),
    ]
